CREATE TABLE `ontime`
(
    `id`                              INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `Year`                            SMALLINT UNSIGNED,
    `Quarter`                         TINYINT UNSIGNED,
    `Month`                           TINYINT UNSIGNED,
    `DayofMonth`                      TINYINT UNSIGNED,
    `DayOfWeek`                       TINYINT UNSIGNED,
    `FlightDate`                      DATE,
    `Reporting_Airline`               VARCHAR(128),
    `DOT_ID_Reporting_Airline`        INT,
    `IATA_CODE_Reporting_Airline`     VARCHAR(128),
    `Tail_Number`                     VARCHAR(128),
    `Flight_Number_Reporting_Airline` VARCHAR(128),
    `OriginAirportID`                 INT,
    `OriginAirportSeqID`              INT,
    `OriginCityMarketID`              INT,
    `Origin`                          VARCHAR(128),
    `OriginCityName`                  VARCHAR(128),
    `OriginState`                     VARCHAR(128),
    `OriginStateFips`                 VARCHAR(128),
    `OriginStateName`                 VARCHAR(128),
    `OriginWac`                       INT,
    `DestAirportID`                   INT,
    `DestAirportSeqID`                INT,
    `DestCityMarketID`                INT,
    `Dest`                            VARCHAR(128),
    `DestCityName`                    VARCHAR(128),
    `DestState`                       VARCHAR(128),
    `DestStateFips`                   VARCHAR(128),
    `DestStateName`                   VARCHAR(128),
    `DestWac`                         INT,
    `CRSDepTime`                      INT,
    `DepTime`                         INT,
    `DepDelay`                        INT,
    `DepDelayMinutes`                 INT,
    `DepDel15`                        INT,
    `DepartureDelayGroups`            VARCHAR(128),
    `DepTimeBlk`                      VARCHAR(128),
    `TaxiOut`                         INT,
    `WheelsOff`                       INT,
    `WheelsOn`                        INT,
    `TaxiIn`                          INT,
    `CRSArrTime`                      INT,
    `ArrTime`                         INT,
    `ArrDelay`                        INT,
    `ArrDelayMinutes`                 INT,
    `ArrDel15`                        INT,
    `ArrivalDelayGroups`              INT,
    `ArrTimeBlk`                      VARCHAR(128),
    `Cancelled`                       TINYINT UNSIGNED,
    `CancellationCode`                VARCHAR(128),
    `Diverted`                        TINYINT UNSIGNED,
    `CRSElapsedTime`                  INT,
    `ActualElapsedTime`               INT,
    `AirTime`                         VARCHAR(128),
    `Flights`                         INT,
    `Distance`                        INT,
    `DistanceGroup`                   TINYINT UNSIGNED,
    `CarrierDelay`                    INT,
    `WeatherDelay`                    INT,
    `NASDelay`                        INT,
    `SecurityDelay`                   INT,
    `LateAircraftDelay`               INT,
    `FirstDepTime`                    VARCHAR(128),
    `TotalAddGTime`                   VARCHAR(128),
    `LongestAddGTime`                 VARCHAR(128),
    `DivAirportLandings`              VARCHAR(128),
    `DivReachedDest`                  VARCHAR(128),
    `DivActualElapsedTime`            VARCHAR(128),
    `DivArrDelay`                     VARCHAR(128),
    `DivDistance`                     VARCHAR(128),
    `Div1Airport`                     VARCHAR(128),
    `Div1AirportID`                   INT,
    `Div1AirportSeqID`                INT,
    `Div1WheelsOn`                    VARCHAR(128),
    `Div1TotalGTime`                  VARCHAR(128),
    `Div1LongestGTime`                VARCHAR(128),
    `Div1WheelsOff`                   VARCHAR(128),
    `Div1TailNum`                     VARCHAR(128),
    `Div2Airport`                     VARCHAR(128),
    `Div2AirportID`                   INT,
    `Div2AirportSeqID`                INT,
    `Div2WheelsOn`                    VARCHAR(128),
    `Div2TotalGTime`                  VARCHAR(128),
    `Div2LongestGTime`                VARCHAR(128),
    `Div2WheelsOff`                   VARCHAR(128),
    `Div2TailNum`                     VARCHAR(128),
    `Div3Airport`                     VARCHAR(128),
    `Div3AirportID`                   INT,
    `Div3AirportSeqID`                INT,
    `Div3WheelsOn`                    VARCHAR(128),
    `Div3TotalGTime`                  VARCHAR(128),
    `Div3LongestGTime`                VARCHAR(128),
    `Div3WheelsOff`                   VARCHAR(128),
    `Div3TailNum`                     VARCHAR(128),
    `Div4Airport`                     VARCHAR(128),
    `Div4AirportID`                   INT,
    `Div4AirportSeqID`                INT,
    `Div4WheelsOn`                    VARCHAR(128),
    `Div4TotalGTime`                  VARCHAR(128),
    `Div4LongestGTime`                VARCHAR(128),
    `Div4WheelsOff`                   VARCHAR(128),
    `Div4TailNum`                     VARCHAR(128),
    `Div5Airport`                     VARCHAR(128),
    `Div5AirportID`                   INT,
    `Div5AirportSeqID`                INT,
    `Div5WheelsOn`                    VARCHAR(128),
    `Div5TotalGTime`                  VARCHAR(128),
    `Div5LongestGTime`                VARCHAR(128),
    `Div5WheelsOff`                   VARCHAR(128),
    `Div5TailNum`                     VARCHAR(128)
);


EXPLAIN
    SELECT avg(c1)FROM (SELECT `Year`, `Month`, count(*) AS c1 FROM ontime GROUP BY `Year`, `Month`) AS t;

# 查询从2000年到2008年每天的航班数
SELECT DayOfWeek, count(*) AS c
FROM ontime
WHERE Year>=2000 AND Year<=2008
GROUP BY DayOfWeek
ORDER BY c DESC;


